### ISSUE TITLE
Major/Minor markings

### ISSUE THREAD

**Issue by nanoxd** [notbenoit/EZClockView#1]
Thanks for the great work! It's awesome to see something like this in `@IBDesignable`. I wanted to see if major/minor markings were in the roadmap? Something along the lines of: 

![watch](https://cloud.githubusercontent.com/assets/1889575/7142955/31cc3540-e291-11e4-86ad-60009a3a0d52.png)

**Comment by notbenoit** [comment]
Hi !
I'm glad to see you enjoyed this clock view !

I might add some new feature like digits and markings in some time (kind of busy right now with AppleWatch release and projects with my daytime job), I'll keep this issue opened to keep track of any future changes related to markings or digits.

**Comment by notbenoit** [comment]
Hi !
I added customizable markings for hours and minutes, enjoy !
![clock](https://cloud.githubusercontent.com/assets/1849419/7294739/58c5d752-e9b0-11e4-8b0d-c8c9bbbdeaaa.png)

**Comment by nanoxd** [comment]
Thanks for the hard work!
![triumph](https://cloud.githubusercontent.com/assets/1889575/7300618/064ef47c-e992-11e4-8a14-480e40e3fc26.gif)
