### ISSUE TITLE
CGPathAddLineToPoint error

### ISSUE THREAD

**Issue by pv-g** [notbenoit/EZClockView#3]
With Xcode 7.2 :
I'm using the view within Interface Builder, everything works great, as expected,
but I get this message in the debugger console on runtime :

`Feb  8 18:04:25  MyProject[46206] <Error>: void CGPathAddLineToPoint(CGMutablePathRef _Nullable, const CGAffineTransform * _Nullable, CGFloat, CGFloat): no current point.`

No graphical glitch noticed, it appears just once, when drawing the clock for the first time, other draws are OK.

**Comment by notbenoit** [comment]
Never noticed this warning before. I'll give it a try and let you know.

**Comment by notbenoit** [comment]
@Philoozushi : Should be fixed in 1.1.2 :+1: 952812477c8c9c3cabce8e8564b6aa9325152015
https://github.com/notbenoit/EZClockView/releases/tag/1.1.2

**Comment by pv-g** [comment]
Awesome reactivity! :smiley_cat: :+1:
Now it would be nice to update the cocoapod too :wink:

**Comment by benoit-fueled** [comment]
Hell yeah totally forgot, I will update that soon! (I've been using Carthage for a while now)

**Comment by notbenoit** [comment]
I updated cocoapods, let me know if you have any trouble!

**Comment by pv-g** [comment]
Yeah, big debate about Cocoapods vs Carthage lately :stuck_out_tongue:
Anyway, the updated Cocoapod works perfectly! :+1:
Thanks again for sharing this good work :smile:
