### ISSUE TITLE
I can't see the clock in storyboard...

### ISSUE THREAD

**Issue by Sweeper777** [notbenoit/EZClockView#5]
Using Xcode 8.3.2, I added a view to the storyboard and set its class to `EZClockView`. I was able to set the `@IBInspectable` properties using the property inspector, but I can't see a clock being drawn in the storyboard. When I run the app, the clock isn't visible either. See [this commit](https://github.com/Sweeper777/TestingArea/tree/2d858687a4961e315a0c59586bf1eebb4c15980e) to reproduce.

**Comment by notbenoit** [comment]
Hey! I’m away from home for a week, I’ll give a look at your issue next week. I think I have enough details to investigate. I’ll keep you posted.

**Comment by notbenoit** [comment]
Gave a shot at your *TestArea* project, It's working, just make sure you set the appropriate **Custom Class** and **Module** to the view
<img width="596" alt="clock" src="https://user-images.githubusercontent.com/1849419/28455052-da5fecc0-6dfd-11e7-977a-195aef894770.png">

**Comment by Sweeper777** [comment]
Oh yeah! I forgot to set the module! It usually is set automatically for me.
