### ISSUE TITLE
Users should also be able to hide a hand by setting its length to 0

### ISSUE THREAD

**Issue by Sweeper777** [notbenoit/EZClockView#6]
I wanted to hide the seconds hand, so I thought I can just set its length to 0, but then it crashed...

I tried to set its thickness to 0 and this time it hid successfully.

I think this is a little counter-intuitive. Can you check the value of the hands' lengths so that if any one is 0, don't draw that hand? Or even better, add properties like `isSecondsHandEnabled` so that users can easily disable some hands.

**Comment by notbenoit** [comment]
So I guess I can close #5 since you managed to display the clock ?
I can give it a look, but I can't give you a timeframe. Feel free to submit a PR first and I'll give it a look.

**Comment by Sweeper777** [comment]
I can see the clock if I create it programmatically, but the clock just won't show in IB.

**Comment by notbenoit** [comment]
The clock displays fine in the `Sample.xib` file provided as a sample with the project. Are you using Auto Layout ?

**Comment by notbenoit** [comment]
You can also hide a handle by setting its color to `UIColor.clear` for now.

**Comment by Sweeper777** [comment]
Yes I am using auto layout

**Comment by notbenoit** [comment]
Closing this one, as setting the color to `UIColor.clear` should be enough for hiding a handle.

**Comment by notbenoit** [comment]
@Sweeper777 Just published `1.2.1` which fixes the crash mentioned above 👌
